os: linux
sudo: 
language: "minimal"
services:
  - docker


jobs:
  include:
    - name: "checks"
      script:
        - chmod 755 scripts/*.sh
        - docker run -v `pwd`:`pwd` -w `pwd` rusdevops/bootstrap-cpp ./scripts/checks.sh
 


notifications:
  email: false
